{\rtf1\ansi\ansicpg1252\deff0\deflang2057{\fonttbl{\f0\fswiss\fcharset0 Arial;}}
{\*\generator Msftedit 5.41.21.2500;}\viewkind4\uc1\pard\f0\fs20 <?xml version="1.0" encoding="UTF-8"?>\par
<!--Created by TIBCO WSDL-->\par
<wsdl:definitions xmlns:tns="http://xmlns.example.com/1285145348265/CMS_UpdateImpl/Business/Processes/NDH__Web__Service" xmlns:ns0="http://www.hp.com/NDH_Web_Service/CMSUpdate" xmlns:ns1="http://www.hp.com/NDH_Web_Service/Fault" xmlns:ns3="http://www.hp.com/NDH_Web_Service/assessmentsummary" xmlns:ns2="http://www.hp.com/NDH_Web_Service/DomainTypes" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Untitled" targetNamespace="http://xmlns.example.com/1285145348265/CMS_UpdateImpl/Business/Processes/NDH__Web__Service">\par
    <wsdl:types>\par
        <xs:schema xmlns:dt="http://www.hp.com/NDH_Web_Service/DomainTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:oraxdb="http://xmlns.oracle.com/xdb" targetNamespace="http://www.hp.com/NDH_Web_Service/DomainTypes" elementFormDefault="qualified" attributeFormDefault="unqualified">\par
            <xs:simpleType name="AddressLine">\par
                <xs:annotation>\par
                    <xs:documentation>Used for all lines of the address other than the postcode</xs:documentation>\par
                </xs:annotation>\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="256"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="CMSNumber">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="20"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="CRONumber">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="12"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="CourtType">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="6"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="ElementCode">\par
                <xs:annotation>\par
                    <xs:documentation>Generic code used for all category and element type fields</xs:documentation>\par
                </xs:annotation>\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="50"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:complexType name="Header">\par
                <xs:sequence>\par
                    <xs:element name="ApplicationMode" type="xs:string"/>\par
                    <xs:element name="CorrelationID" type="xs:string"/>\par
                    <xs:element name="OASysRUsername" type="xs:string"/>\par
                    <xs:element oraxdb:SQLType="TIMESTAMP WITH TIME ZONE" name="MessageTimestamp" type="xs:dateTime"/>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:simpleType name="ICMSRef">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="32"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:complexType name="ICMSReference">\par
                <xs:annotation>\par
                    <xs:documentation>ICMS Elements used to uniquely identify an offender and event</xs:documentation>\par
                </xs:annotation>\par
                <xs:sequence>\par
                    <xs:element name="RefClient" type="dt:ICMSRef">\par
                        <xs:annotation>\par
                            <xs:documentation>Only used for the ICMS to identify a unique offender/Event combination</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="RefLink" type="xs:anyType">\par
                        <xs:annotation>\par
                            <xs:documentation>Only used for the ICMS to identify a unique offender/Event combination</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="RefSupervision" type="xs:anyType">\par
                        <xs:annotation>\par
                            <xs:documentation>Only used for the ICMS to identify a unique offender/Event combination</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:simpleType name="Numeric10">\par
                <xs:restriction base="xs:integer">\par
                    <xs:maxInclusive value="10"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:complexType name="OffenceDetail">\par
                <xs:sequence>\par
                    <xs:element name="OffenceGroupCode" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>3 digita Home Office Code i.e. "002"</xs:documentation>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="3"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="OffenceSubCode" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>2 Digit Home Office sub code i.e. "01"</xs:documentation>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="2"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="AdditionalIndicator" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>Only one offence will be maked as N, all others will be set to Y</xs:documentation>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="1"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:simpleType name="PNCNumber">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="20"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="PersonName">\par
                <xs:annotation>\par
                    <xs:documentation>Standard offender name type</xs:documentation>\par
                </xs:annotation>\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="100"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="PhoneNumber">\par
                <xs:annotation>\par
                    <xs:documentation>Standard telephone number type</xs:documentation>\par
                </xs:annotation>\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="20"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="PostCode">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="32"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="PrisonNumber">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="6"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:complexType name="Risk">\par
                <xs:sequence>\par
                    <xs:element name="RiskofHarm" type="dt:ElementCode"/>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:simpleType name="SharedKeyCode">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="100"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="Text100">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="100"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="Text2">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="2"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="VeryLargeText">\par
                <xs:annotation>\par
                    <xs:documentation>Maps to an Oracle CLOB item</xs:documentation>\par
                </xs:annotation>\par
                <xs:restriction base="xs:string"/>\par
            </xs:simpleType>\par
            <xs:element name="MessageID">\par
                <xs:annotation>\par
                    <xs:documentation>Unique message ID to be used for associating a request sent to National Delius with a response received.</xs:documentation>\par
                </xs:annotation>\par
                <xs:simpleType>\par
                    <xs:restriction base="xs:string">\par
                        <xs:maxLength value="30"/>\par
                    </xs:restriction>\par
                </xs:simpleType>\par
            </xs:element>\par
        </xs:schema>\par
        <xs:schema xmlns:dt="http://www.hp.com/NDH_Web_Service/DomainTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.hp.com/NDH_Web_Service/assessmentsummary" targetNamespace="http://www.hp.com/NDH_Web_Service/assessmentsummary" elementFormDefault="qualified" attributeFormDefault="unqualified">\par
            <xs:import namespace="http://www.hp.com/NDH_Web_Service/DomainTypes"/>\par
            <xs:complexType name="Assessment">\par
                <xs:sequence>\par
                    <xs:element name="CMSProbNumber" type="dt:CMSNumber"/>\par
                    <xs:choice>\par
                        <xs:element name="EventNumber" type="xs:integer">\par
                            <xs:annotation>\par
                                <xs:documentation>Relates to Event Number from PCMS or Seq Numbe from Legacy</xs:documentation>\par
                            </xs:annotation>\par
                        </xs:element>\par
                        <xs:element name="ICMSReference" type="dt:ICMSReference"/>\par
                    </xs:choice>\par
                    <xs:element name="OffenderGUID" type="xs:integer">\par
                        <xs:annotation>\par
                            <xs:documentation>Primary key for the offender record in OASysR</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="DateAssessmentCompleted" type="xs:date" minOccurs="0"/>\par
                    <xs:element name="DeletedIndicator" type="xs:integer" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>Set to "1" if deleted</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="AssessmentGUID" type="xs:integer">\par
                        <xs:annotation>\par
                            <xs:documentation>Primary Key of the Assessment</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="RiskFlags" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>Comma Separated list of Risk flags i.e. "N", "L", "M", "H", "V"</xs:documentation>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="50"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="ConcernFlags" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>Comma separated List of Concern codes i.e. "YES", "NO, "DK", "N/A"</xs:documentation>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="50"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="TotalScore" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>OVP + OGP total score</xs:documentation>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="10"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="PurposeOfAssessmentCode" type="dt:ElementCode" minOccurs="0"/>\par
                    <xs:element name="PurposeOfAssessmentDescription" minOccurs="0">\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="50"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="DateCreated" type="xs:date"/>\par
                    <xs:element name="AssessedBy" type="dt:PersonName" minOccurs="0"/>\par
                    <xs:element name="CourtCode" type="dt:SharedKeyCode" minOccurs="0"/>\par
                    <xs:element name="CourtType" type="dt:CourtType" minOccurs="0"/>\par
                    <xs:element name="CourtName" type="dt:Text100" minOccurs="0"/>\par
                    <xs:element name="Offence" type="dt:OffenceDetail" minOccurs="0"/>\par
                    <xs:element name="OGRSScore1" type="xs:decimal" minOccurs="0"/>\par
                    <xs:element name="OGRSScore2" type="xs:decimal" minOccurs="0"/>\par
                    <xs:element name="SentencePlanInitialDate" type="xs:date" minOccurs="0"/>\par
                    <xs:element name="SentencePlanReviewDate" type="xs:date" minOccurs="0"/>\par
                    <xs:element name="ReviewTerminated" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>"Y" if terminated</xs:documentation>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="1"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="ReviewNumber" minOccurs="0">\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="20"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="OGPNotCalculated" type="xs:integer" minOccurs="0"/>\par
                    <xs:element name="OVPNotCalculated" type="xs:integer" minOccurs="0"/>\par
                    <xs:element name="OGPScore1" type="xs:integer" minOccurs="0"/>\par
                    <xs:element name="OGPScore2" type="xs:integer" minOccurs="0"/>\par
                    <xs:element name="OVPScore1" type="xs:integer" minOccurs="0"/>\par
                    <xs:element name="OVPScore2" type="xs:integer" minOccurs="0"/>\par
                    <xs:element name="OGRSRiskRecon" type="dt:ElementCode" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OGRSRiskRecon</xs:appinfo>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="OGPRiskRecon" type="dt:ElementCode" minOccurs="0"/>\par
                    <xs:element name="OVPRiskRecon" type="dt:ElementCode" minOccurs="0"/>\par
                    <xs:element name="LayerType" type="dt:ElementCode"/>\par
                    <xs:element name="Section3CrimScore" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASYSSection3Scores</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="10"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Section4CrimScore" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASYSSection4Scores</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="10"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Section6CrimScore" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASYSSection6Scores</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="10"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Section7CrimScore" type="xs:string" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASYSSection7Scores</xs:appinfo>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="Section8CrimScore" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASYSSection8Scores</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="10"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Section9CrimScore" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASYSSection9Scores</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="10"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Section11CrimScore" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASYSSection11Scores</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="10"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Section12CrimScore" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASYSSection12Scores</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="10"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="LAOIndicator" type="xs:string" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.LAO</xs:appinfo>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="TierCode" minOccurs="0">\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="1"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Layer1Obj" type="xs:string" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>Comma Separated list of values</xs:documentation>\par
                            <xs:appinfo>Offender.OASYSAssessment.Layer1Obj</xs:appinfo>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="Risk" type="dt:Risk" minOccurs="0"/>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:complexType name="Objective">\par
                <xs:sequence>\par
                    <xs:element name="ObjectiveDescription">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.Objective</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="ObjectiveStatus">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.Objective</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="ObjectiveNumber" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.Objective</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Need1" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.Need1</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Need2" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.Need2</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Need3" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.Need3</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="Need4" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.Need4</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="ActionCode1" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.WorkSummary1</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="ActionText1" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.Text1</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="ActionCode2" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.WorkSummary1</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="ActionText2" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.Text1</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="ActionCode3" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.WorkSummary1</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="ActionText3" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:appinfo>Offender.OASYSAssessment.OASysSentencePlan.Text1</xs:appinfo>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="4000"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                </xs:sequence>\par
            </xs:complexType>\par
        </xs:schema>\par
        <xs:schema xmlns:as="http://www.hp.com/NDH_Web_Service/assessmentsummary" xmlns:dt="http://www.hp.com/NDH_Web_Service/DomainTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hp.com/NDH_Web_Service/CMSUpdate" elementFormDefault="qualified" attributeFormDefault="unqualified">\par
            <xs:import namespace="http://www.hp.com/NDH_Web_Service/DomainTypes"/>\par
            <xs:import namespace="http://www.hp.com/NDH_Web_Service/assessmentsummary"/>\par
            <xs:element name="CMSUpdate">\par
                <xs:annotation>\par
                    <xs:documentation>Comment describing your root element</xs:documentation>\par
                </xs:annotation>\par
                <xs:complexType>\par
                    <xs:sequence>\par
                        <xs:element name="Header" type="dt:Header"/>\par
                        <xs:element name="Assessment" type="as:Assessment"/>\par
                        <xs:element name="Objective" type="as:Objective" minOccurs="0" maxOccurs="unbounded"/>\par
                    </xs:sequence>\par
                </xs:complexType>\par
            </xs:element>\par
        </xs:schema>\par
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.hp.com/NDH_Web_Service/Fault" targetNamespace="http://www.hp.com/NDH_Web_Service/Fault" elementFormDefault="qualified" attributeFormDefault="unqualified">\par
            <xs:complexType name="ErrorType">\par
                <xs:sequence>\par
                    <xs:element name="Code" type="xs:string">\par
                        <xs:annotation>\par
                            <xs:documentation>A unique code identifying the type of this fault.</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="Description" type="xs:string">\par
                        <xs:annotation>\par
                            <xs:documentation>Containing specific details for an error, e.g. - 'Offender with CRN 1234567' could not be found'.</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="Timestamp" type="xs:dateTime"/>\par
                    <xs:element name="RequestMessage" type="xs:string">\par
                        <xs:annotation>\par
                            <xs:documentation>The contents of the SOAP request body that caused this fault</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:element name="AuthorisationFailureException" type="ns1:ErrorType">\par
                <xs:annotation>\par
                    <xs:documentation>Used to indicate that the client is not authorised to access the requested service.</xs:documentation>\par
                </xs:annotation>\par
            </xs:element>\par
            <xs:element name="BusinessException" type="ns1:ErrorType">\par
                <xs:annotation>\par
                    <xs:documentation>Used to indicate that a business error occured that prevented the request from being fulfilled, e.g. -' Offender with CRN 1234567' could not be found'.</xs:documentation>\par
                </xs:annotation>\par
            </xs:element>\par
            <xs:element name="Fault">\par
                <xs:complexType>\par
                    <xs:sequence>\par
                        <xs:element ref="ns1:AuthorisationFailureException" minOccurs="0">\par
                            <xs:annotation>\par
                                <xs:documentation>Used to indicate that the client is not authorised to access the requested service.</xs:documentation>\par
                            </xs:annotation>\par
                        </xs:element>\par
                        <xs:element ref="ns1:BusinessException" minOccurs="0">\par
                            <xs:annotation>\par
                                <xs:documentation>Used to indicate that a business error occured that prevented the request from being fulfilled, e.g. -' Offender with CRN 1234567' could not be found'.</xs:documentation>\par
                            </xs:annotation>\par
                        </xs:element>\par
                        <xs:element ref="ns1:ServerRuntimeException" minOccurs="0">\par
                            <xs:annotation>\par
                                <xs:documentation>Used to indicate that an unexpected problem occurred during server side processing that has prevented the request from being fulfilled, e.g.-  database constraint violation when attemping to persist new data from IAPS or eOASys.</xs:documentation>\par
                            </xs:annotation>\par
                        </xs:element>\par
                        <xs:element ref="ns1:ValidationFailureException" minOccurs="0">\par
                            <xs:annotation>\par
                                <xs:documentation>Used to indicate that the incoming request is not valid according to the schema.</xs:documentation>\par
                            </xs:annotation>\par
                        </xs:element>\par
                    </xs:sequence>\par
                </xs:complexType>\par
            </xs:element>\par
            <xs:element name="ServerRuntimeException" type="ns1:ErrorType">\par
                <xs:annotation>\par
                    <xs:documentation>Used to indicate that an unexpected problem occurred during server side processing that has prevented the request from being fulfilled, e.g.-  database constraint violation when attemping to persist new data from IAPS or eOASys.</xs:documentation>\par
                </xs:annotation>\par
            </xs:element>\par
            <xs:element name="ValidationFailureException" type="ns1:ErrorType">\par
                <xs:annotation>\par
                    <xs:documentation>Used to indicate that the incoming request is not valid according to the schema.</xs:documentation>\par
                </xs:annotation>\par
            </xs:element>\par
        </xs:schema>\par
    </wsdl:types>\par
    <wsdl:service name="NDH__Web__Service__CMS__Update">\par
        <wsdl:port name="SOAPEventSource" binding="tns:SOAPEventSourceBinding">\par
            <soap:address location="http://localhost:8555/Business/Processes/NDH_Web_Service/NDH_Web_Service_CMS_Update"/>\par
        </wsdl:port>\par
    </wsdl:service>\par
    <wsdl:portType name="NDH_PortType">\par
        <wsdl:operation name="CMS_Update">\par
            <wsdl:input message="tns:CMS_Update"/>\par
            <wsdl:fault name="fault1" message="tns:Fault_Report"/>\par
        </wsdl:operation>\par
    </wsdl:portType>\par
    <wsdl:binding name="SOAPEventSourceBinding" type="tns:NDH_PortType">\par
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>\par
        <wsdl:operation name="CMS_Update">\par
            <soap:operation style="document" soapAction="/Business/Processes/NDH_Web_Service/NDH_Web_Service_CMS_Update" soapActionRequired="true"/>\par
            <wsdl:input>\par
                <soap:body use="literal" parts="request"/>\par
            </wsdl:input>\par
            <wsdl:fault name="fault1">\par
                <soap:fault use="literal" name="fault1"/>\par
            </wsdl:fault>\par
        </wsdl:operation>\par
    </wsdl:binding>\par
    <wsdl:message name="CMS_Update">\par
        <wsdl:part name="request" element="ns0:CMSUpdate"/>\par
    </wsdl:message>\par
    <wsdl:message name="Fault_Report">\par
        <wsdl:part name="fault" element="ns1:Fault"/>\par
    </wsdl:message>\par
</wsdl:definitions>\par
}
 