{\rtf1\ansi\ansicpg1252\deff0\deflang2057{\fonttbl{\f0\fswiss\fcharset0 Arial;}}
{\*\generator Msftedit 5.41.21.2500;}\viewkind4\uc1\pard\f0\fs20 <?xml version="1.0" encoding="UTF-8"?>\par
<!--Created by TIBCO WSDL-->\par
<wsdl:definitions
        xmlns:tns="http://xmlns.example.com/1285145348265/Risk_UpdateImpl/Business/Processes/NDH__Web__Service"
        xmlns:ns0="http://www.hp.com/NDH_Web_Service/riskupdaterequest"
        xmlns:ns1="http://www.hp.com/NDH_Web_Service/riskupdateresponse"
        xmlns:ns2="http://www.hp.com/NDH_Web_Service/Fault" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Untitled"
        targetNamespace="http://xmlns.example.com/1285145348265/Risk_UpdateImpl/Business/Processes/NDH__Web__Service">\par
    <wsdl:types>\par
        <xs:schema xmlns:dt="http://www.hp.com/NDH_Web_Service/DomainTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:oraxdb="http://xmlns.oracle.com/xdb" targetNamespace="http://www.hp.com/NDH_Web_Service/DomainTypes" elementFormDefault="qualified" attributeFormDefault="unqualified">\par
            <xs:simpleType name="AddressLine">\par
                <xs:annotation>\par
                    <xs:documentation>Used for all lines of the address other than the postcode</xs:documentation>\par
                </xs:annotation>\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="256"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="CMSNumber">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="20"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="CRONumber">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="12"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="CourtType">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="6"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="ElementCode">\par
                <xs:annotation>\par
                    <xs:documentation>Generic code used for all category and element type fields</xs:documentation>\par
                </xs:annotation>\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="50"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:complexType name="Header">\par
                <xs:sequence>\par
                    <xs:element name="ApplicationMode" type="xs:string"/>\par
                    <xs:element name="CorrelationID" type="xs:string"/>\par
                    <xs:element name="OASysRUsername" type="xs:string"/>\par
                    <xs:element oraxdb:SQLType="TIMESTAMP WITH TIME ZONE" name="MessageTimestamp" type="xs:dateTime"/>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:simpleType name="ICMSRef">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="32"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:complexType name="ICMSReference">\par
                <xs:annotation>\par
                    <xs:documentation>ICMS Elements used to uniquely identify an offender and event</xs:documentation>\par
                </xs:annotation>\par
                <xs:sequence>\par
                    <xs:element name="RefClient" type="dt:ICMSRef">\par
                        <xs:annotation>\par
                            <xs:documentation>Only used for the ICMS to identify a unique offender/Event combination</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="RefLink" type="xs:anyType">\par
                        <xs:annotation>\par
                            <xs:documentation>Only used for the ICMS to identify a unique offender/Event combination</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="RefSupervision" type="xs:anyType">\par
                        <xs:annotation>\par
                            <xs:documentation>Only used for the ICMS to identify a unique offender/Event combination</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:simpleType name="Numeric10">\par
                <xs:restriction base="xs:integer">\par
                    <xs:maxInclusive value="10"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:complexType name="OffenceDetail">\par
                <xs:sequence>\par
                    <xs:element name="OffenceGroupCode" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>3 digita Home Office Code i.e. "002"</xs:documentation>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="3"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="OffenceSubCode" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>2 Digit Home Office sub code i.e. "01"</xs:documentation>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="2"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                    <xs:element name="AdditionalIndicator" minOccurs="0">\par
                        <xs:annotation>\par
                            <xs:documentation>Only one offence will be maked as N, all others will be set to Y</xs:documentation>\par
                        </xs:annotation>\par
                        <xs:simpleType>\par
                            <xs:restriction base="xs:string">\par
                                <xs:maxLength value="1"/>\par
                            </xs:restriction>\par
                        </xs:simpleType>\par
                    </xs:element>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:simpleType name="PNCNumber">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="20"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="PersonName">\par
                <xs:annotation>\par
                    <xs:documentation>Standard offender name type</xs:documentation>\par
                </xs:annotation>\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="100"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="PhoneNumber">\par
                <xs:annotation>\par
                    <xs:documentation>Standard telephone number type</xs:documentation>\par
                </xs:annotation>\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="20"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="PostCode">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="32"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="PrisonNumber">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="6"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:complexType name="Risk">\par
                <xs:sequence>\par
                    <xs:element name="RiskofHarm" type="dt:ElementCode"/>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:simpleType name="SharedKeyCode">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="100"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="Text100">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="100"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="Text2">\par
                <xs:restriction base="xs:string">\par
                    <xs:maxLength value="2"/>\par
                </xs:restriction>\par
            </xs:simpleType>\par
            <xs:simpleType name="VeryLargeText">\par
                <xs:annotation>\par
                    <xs:documentation>Maps to an Oracle CLOB item</xs:documentation>\par
                </xs:annotation>\par
                <xs:restriction base="xs:string"/>\par
            </xs:simpleType>\par
            <xs:element name="MessageID">\par
                <xs:annotation>\par
                    <xs:documentation>Unique message ID to be used for associating a request sent to National Delius with a response received.</xs:documentation>\par
                </xs:annotation>\par
                <xs:simpleType>\par
                    <xs:restriction base="xs:string">\par
                        <xs:maxLength value="30"/>\par
                    </xs:restriction>\par
                </xs:simpleType>\par
            </xs:element>\par
        </xs:schema>\par
        <xs:schema xmlns:dt="http://www.hp.com/NDH_Web_Service/DomainTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.hp.com/NDH_Web_Service/riskupdateresponse" targetNamespace="http://www.hp.com/NDH_Web_Service/riskupdateresponse" elementFormDefault="qualified" attributeFormDefault="unqualified">\par
            <xs:import namespace="http://www.hp.com/NDH_Web_Service/DomainTypes"/>\par
            <xs:element name="RiskUpdateResponse">\par
                <xs:complexType>\par
                    <xs:sequence>\par
                        <xs:element name="header" type="dt:Header"/>\par
                        <xs:element name="CaseReferenceNumber" type="xs:string">\par
                            <xs:annotation>\par
                                <xs:appinfo>Offender.CRN</xs:appinfo>\par
                            </xs:annotation>\par
                        </xs:element>\par
                    </xs:sequence>\par
                </xs:complexType>\par
            </xs:element>\par
        </xs:schema>\par
        <xs:schema xmlns:dt="http://www.hp.com/NDH_Web_Service/DomainTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.hp.com/NDH_Web_Service/riskupdaterequest" targetNamespace="http://www.hp.com/NDH_Web_Service/riskupdaterequest" elementFormDefault="qualified" attributeFormDefault="unqualified">\par
            <xs:import namespace="http://www.hp.com/NDH_Web_Service/DomainTypes"/>\par
            <xs:element name="RiskUpdateRequest">\par
                <xs:annotation>\par
                    <xs:documentation>Comment describing your root element</xs:documentation>\par
                </xs:annotation>\par
                <xs:complexType>\par
                    <xs:sequence>\par
                        <xs:element name="header" type="dt:Header"/>\par
                        <xs:element name="CMSProbNumber" type="dt:CMSNumber"/>\par
                        <xs:element name="Risk" type="dt:Risk"/>\par
                        <xs:element name="RiskFlags">\par
                            <xs:simpleType>\par
                                <xs:restriction base="xs:string">\par
                                    <xs:maxLength value="50"/>\par
                                </xs:restriction>\par
                            </xs:simpleType>\par
                        </xs:element>\par
                    </xs:sequence>\par
                </xs:complexType>\par
            </xs:element>\par
        </xs:schema>\par
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.hp.com/NDH_Web_Service/Fault" targetNamespace="http://www.hp.com/NDH_Web_Service/Fault" elementFormDefault="qualified" attributeFormDefault="unqualified">\par
            <xs:complexType name="ErrorType">\par
                <xs:sequence>\par
                    <xs:element name="Code" type="xs:string">\par
                        <xs:annotation>\par
                            <xs:documentation>A unique code identifying the type of this fault.</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="Description" type="xs:string">\par
                        <xs:annotation>\par
                            <xs:documentation>Containing specific details for an error, e.g. - 'Offender with CRN 1234567' could not be found'.</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                    <xs:element name="Timestamp" type="xs:dateTime"/>\par
                    <xs:element name="RequestMessage" type="xs:string">\par
                        <xs:annotation>\par
                            <xs:documentation>The contents of the SOAP request body that caused this fault</xs:documentation>\par
                        </xs:annotation>\par
                    </xs:element>\par
                </xs:sequence>\par
            </xs:complexType>\par
            <xs:element name="AuthorisationFailureException" type="ns2:ErrorType">\par
                <xs:annotation>\par
                    <xs:documentation>Used to indicate that the client is not authorised to access the requested service.</xs:documentation>\par
                </xs:annotation>\par
            </xs:element>\par
            <xs:element name="BusinessException" type="ns2:ErrorType">\par
                <xs:annotation>\par
                    <xs:documentation>Used to indicate that a business error occured that prevented the request from being fulfilled, e.g. -' Offender with CRN 1234567' could not be found'.</xs:documentation>\par
                </xs:annotation>\par
            </xs:element>\par
            <xs:element name="Fault">\par
                <xs:complexType>\par
                    <xs:sequence>\par
                        <xs:element ref="ns2:AuthorisationFailureException" minOccurs="0">\par
                            <xs:annotation>\par
                                <xs:documentation>Used to indicate that the client is not authorised to access the requested service.</xs:documentation>\par
                            </xs:annotation>\par
                        </xs:element>\par
                        <xs:element ref="ns2:BusinessException" minOccurs="0">\par
                            <xs:annotation>\par
                                <xs:documentation>Used to indicate that a business error occured that prevented the request from being fulfilled, e.g. -' Offender with CRN 1234567' could not be found'.</xs:documentation>\par
                            </xs:annotation>\par
                        </xs:element>\par
                        <xs:element ref="ns2:ServerRuntimeException" minOccurs="0">\par
                            <xs:annotation>\par
                                <xs:documentation>Used to indicate that an unexpected problem occurred during server side processing that has prevented the request from being fulfilled, e.g.-  database constraint violation when attemping to persist new data from IAPS or eOASys.</xs:documentation>\par
                            </xs:annotation>\par
                        </xs:element>\par
                        <xs:element ref="ns2:ValidationFailureException" minOccurs="0">\par
                            <xs:annotation>\par
                                <xs:documentation>Used to indicate that the incoming request is not valid according to the schema.</xs:documentation>\par
                            </xs:annotation>\par
                        </xs:element>\par
                    </xs:sequence>\par
                </xs:complexType>\par
            </xs:element>\par
            <xs:element name="ServerRuntimeException" type="ns2:ErrorType">\par
                <xs:annotation>\par
                    <xs:documentation>Used to indicate that an unexpected problem occurred during server side processing that has prevented the request from being fulfilled, e.g.-  database constraint violation when attemping to persist new data from IAPS or eOASys.</xs:documentation>\par
                </xs:annotation>\par
            </xs:element>\par
            <xs:element name="ValidationFailureException" type="ns2:ErrorType">\par
                <xs:annotation>\par
                    <xs:documentation>Used to indicate that the incoming request is not valid according to the schema.</xs:documentation>\par
                </xs:annotation>\par
            </xs:element>\par
        </xs:schema>\par
    </wsdl:types>\par
    <wsdl:service name="NDH__Web__Service__Risk__Update">\par
        <wsdl:port name="SOAPEventSource" binding="tns:SOAPEventSourceBinding">\par
            <soap:address location="http://localhost:8555/Business/Processes/NDH_Web_Service/NDH_Web_Service_Risk_Update"/>\par
        </wsdl:port>\par
    </wsdl:service>\par
    <wsdl:portType name="NDH_PortType">\par
        <wsdl:operation name="Risk_Update">\par
            <wsdl:input message="tns:Risk_Update_Request"/>\par
            <wsdl:output message="tns:Risk_Update_Response"/>\par
            <wsdl:fault name="fault1" message="tns:Fault_Report"/>\par
        </wsdl:operation>\par
    </wsdl:portType>\par
    <wsdl:binding name="SOAPEventSourceBinding" type="tns:NDH_PortType">\par
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>\par
        <wsdl:operation name="Risk_Update">\par
            <soap:operation style="document" soapAction="/Business/Processes/NDH_Web_Service/NDH_Web_Service_Risk_Update" soapActionRequired="true"/>\par
            <wsdl:input>\par
                <soap:body use="literal" parts="request"/>\par
            </wsdl:input>\par
            <wsdl:output>\par
                <soap:body use="literal" parts="response"/>\par
            </wsdl:output>\par
            <wsdl:fault name="fault1">\par
                <soap:fault use="literal" name="fault1"/>\par
            </wsdl:fault>\par
        </wsdl:operation>\par
    </wsdl:binding>\par
    <wsdl:message name="Risk_Update_Request">\par
        <wsdl:part name="request" element="ns0:RiskUpdateRequest"/>\par
    </wsdl:message>\par
    <wsdl:message name="Risk_Update_Response">\par
        <wsdl:part name="response" element="ns1:RiskUpdateResponse"/>\par
    </wsdl:message>\par
    <wsdl:message name="Fault_Report">\par
        <wsdl:part name="fault" element="ns2:Fault"/>\par
    </wsdl:message>\par
</wsdl:definitions>\par
}
 